---
- name: Stop Node Exporter service
  systemd:
    name: node_exporter
    state: stopped
    enabled: no

- name: Remove Node Exporter binary
  file:
    path: /usr/local/bin/node_exporter
    state: absent

- name: Remove Node Exporter service
  file:
    path: /etc/systemd/system/node_exporter.service
    state: absent

- name: Remove Node Exporter temp files
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - /tmp/node_exporter*

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes