{
 "title": "[Overview] Backup Infras",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "Worker",
    "label": "Worker",
    "query": {
     "query": "label_values(node_os_info,instance)"
    }
   },
   {
    "name": "Interval",
    "label": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Percent Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"$Worker:9100\"}[$Interval])) * 100)",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Memory Percent Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$Worker:9100\"} - node_memory_MemAvailable_bytes{instance=\"$Worker:9100\"}) / node_memory_MemTotal_bytes{instance=\"$Worker:9100\"} * 100",
     "legendFormat": "{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Zpool Percent Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{fstype=\"zfs\",instance=\"$Worker:9100\"} / node_filesystem_size_bytes{fstype=\"zfs\",instance=\"$Worker:9100\"}) * 100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Zpool Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=\"zfs\",instance=\"$Worker:9100\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Total queues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_total_queue{instance=\"$Worker:16499\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Volume Backup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_details_queue{instance=\"$Worker:16499\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Process Backup",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_process{instance=\"$Worker:16499\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Percent Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\",instance=\"$Worker:9100\"}[$Interval])) * 100)",
     "legendFormat": "$Worker"
    }
   ]
  },
  {
   "title": "Memory Percent Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$Worker:9100\"} - node_memory_MemAvailable_bytes{instance=\"$Worker:9100\"}) / node_memory_MemTotal_bytes{instance=\"$Worker:9100\"} * 100",
     "legendFormat": "$Worker"
    }
   ]
  },
  {
   "title": "Total Volume Backup",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_details_queue{instance=\"$Worker:16499\"}) by (rabbitmq_host, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Process Backup",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "total_process{instance=\"$Worker:16499\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IOPS Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "zpool_write_ops{instance=\"$Worker:16499\"}",
     "legendFormat": "{{name}} - {{member}}: {{__name__}}"
    }
   ]
  },
  {
   "title": "IOPS Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "zpool_read_ops{instance=\"$Worker:16499\"}",
     "legendFormat": "{{name}} - {{member}}: {{__name__}}"
    }
   ]
  },
  {
   "title": "Network Traffic ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\", instance=\"$Worker:9100\"}[$Interval])",
     "legendFormat": "Traffic in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\", instance=\"$Worker:9100\"}[$Interval])",
     "legendFormat": "Traffic out"
    }
   ]
  },
  {
   "title": "Top 10 Hard Disk IOPS Write ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk(10,zpool_write_ops{instance=\"$Worker:16499\",member=~\"sd.*\"})",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Top 10 Hard Disk IOPS Read ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk(10,zpool_read_ops{instance=\"$Worker:16499\",member=~\"sd.*\"})",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "ZFS Resource summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "zpool_member_status{instance=\"$Worker:16499\"}"
    }
   ]
  }
 ]
}